[build]
base = "ubuntu"

[build.environment]
DOTNET_VERSION = "8.0"

[phases.setup]
cmds = [
    "curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh",
    "chmod +x dotnet-install.sh",
    "./dotnet-install.sh --version 8.0.100",
    "export PATH=$HOME/.dotnet:$PATH"
]

[phases.build]
cmds = [
    "export PATH=$HOME/.dotnet:$PATH",
    "dotnet restore",
    "dotnet publish -c Release -o /app/publish"
]

[start]
cmd = "dotnet /app/publish/Ravioli.dll"